### ISSUE TITLE
Misspelled Ethereum on main page

### ISSUE THREAD

**Issue by tesla809** [nczhu/solidity-koans#47]
Love the project. But I notice you misspelt Ethereum on your main page.

You place 
"Learn **Etherem** programming through test driven development. The Koans walk you along the path to enlightenment in order to learn Solidity - as inspired by Ruby Koans."

Instead of:

"Learn **Ethereum** programming through test driven development. The Koans walk you along the path to enlightenment in order to learn Solidity - as inspired by Ruby Koans."

**Comment by soulofamachine** [comment]
thanks fixed!
